app/config/routes.rb
# encoding: utf-8
App::Application.routes.draw do
  root 'welcome#index'

  get 'projects' => 'project#index'
  get 'login'    => 'login#index'

  resources :project do
    resources :task
  end
end

app/app/models/project.rb
# encoding: utf-8
# app/models/project.rb
# Project model
class Project < ActiveRecord::Base
  has_many :tasks
  belongs_to :user
end

app/app/models/task.rb
# encoding: utf-8
# app/models/task.rb
# Task model
class Task < ActiveRecord::Base
  belongs_to :project
end

app/app/models/user.rb
# encoding: utf-8
# app/models/user.rb
# User model
class User < ActiveRecord::Base
  has_many :projects
  has_one :userproperty
  validates_uniqueness_of :username
end

app/app/models/userproperty.rb
# encoding: utf-8
# app/models/userproperty.rb
# Userproperty model
class Userproperty < ActiveRecord::Base
  belongs_to :user
end

app/app/controllers/application_controller.rb
# encoding: utf-8
# app/controllers/application_controller.rb
# class
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/app/controllers/login_controller.rb
# encoding: utf-8
# app/controllers/login_controller.rb
# Login controller
class LoginController < ApplicationController
  def index
  end
end

app/app/controllers/project_controller.rb
# encoding: utf-8
# app/controllers/project_controller.rb
# Project controller
class ProjectController < ApplicationController
  def index
    @projects = Project.all
    respond_to do |format|
      format.html
      format.json do
        render json: @projects
      end
      format.xml do
        render xml: @projects
      end
    end
  end

  def show
    @project = Project.find(params[:id])
    respond_to do |format|
      format.html
      format.json do
        render json: @project
      end
      format.xml do
        render xml: @project
      end
    end
  end
end

app/app/controllers/task_controller.rb
# encoding: utf-8
# app/controllers/task_controller.rb
# Task controller
class TaskController < ApplicationController
  def index
    @tasks = Project.find(params[:project_id]).tasks
  end

  def show
    project = Project.find(params[:project_id])
    @task   = project.tasks.find(params[:id])
  end
end

app/app/controllers/welcome_controller.rb
# encoding: utf-8
# app/controllers/welcome_controller.rb
# Welcome controller
class WelcomeController < ApplicationController
  def index
    @page_title = 'Life Organiser Weapon'
  end
end

app/app/helpers/application_helper.rb
# encoding: utf-8
# app/helpers/application_helper.rb
# ApplicationHelper
module ApplicationHelper
end

app/app/helpers/welcome_helper.rb
# encoding: utf-8
# app/helpers/welcome_helper.rb
# WelcomeHelper module
module WelcomeHelper
end

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title %></title>
  <%= stylesheet_link_tag     'application', media: 'all' %>
  <%= favicon_link_tag        'favicon.ico', type: 'image/x-icon' %>
  <%= javascript_include_tag  'http://use.edgefonts.net/open-sans:n7,i7,n8,i8,i4,n3,i3,n4,n6,i6:all.js' %>
  <%= javascript_include_tag  'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
  <%= yield %>
</div>
</body>
</html>

app/app/views/login/index.html.erb
<h1>Login</h1>

app/app/views/project/index.html.erb
<h1>Projects</h1>
<% @projects.each do |project| %>
  <h2><%= link_to project.name, project_path(project.id) %></h2>
  <p><%= project.description %></p>
<% end %>

app/app/views/project/show.html.erb
<h1><%= @project.name %></h1>
<p><%= @project.description %></p>
<h2>Tasks</h2>
<ul>
  <% @project.tasks.each do |task| %>
  <li><%= link_to task.name, project_task_path(@project.id, task.id) %></li>
  <% end %>
</ul>
<h2>Add new task</h2>
<%= link_to 'New task', new_project_task_path(@project.id) %>

app/app/views/project/tasks.html.erb
<% @tasks.each do |task| %>
  <h1><%= task.name %></h1>
  <p><%= task.description %></p>
<% end %>

app/app/views/task/index.html.erb
<h1>Tasks</h1>
<% @tasks.each do |task| %>
  <h1><%= task.name %></h1>
  <p><%= task.description %></p>
<% end %>

app/app/views/task/show.html.erb
<h1><%= @task.name %></h1>
<p><%= @task.description %></p>

app/app/views/welcome/index.html.erb
<h1>Life Organiser Weapon</h1>

<%= link_to 'Show projects', project_index_path %>